DROP TABLE IF EXISTS Trainee CASCADE;
DROP TABLE IF EXISTS Trainer CASCADE;
DROP TABLE IF EXISTS Trainer_TrainingType CASCADE;
DROP TABLE IF EXISTS Training CASCADE;
DROP TABLE IF EXISTS TrainingType CASCADE;
DROP TABLE IF EXISTS UserEntity CASCADE;


CREATE TABLE Trainee (dateOfBirth date, id bigint generated by default as identity, user_id bigint unique, primary key (id));
CREATE TABLE Trainer (id bigint generated by default as identity, user_id bigint unique, primary key (id));
CREATE TABLE Trainer_TrainingType (Trainer_id bigint not null, specializations_id bigint not null unique);
CREATE TABLE Training (trainingDuration numeric(21,0) not null, id bigint generated by default as identity, trainee_id bigint, trainer_id bigint, trainingDate timestamp(6) not null, trainingType_id bigint, trainingName varchar(255) not null, primary key (id));
CREATE TABLE TrainingType (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
CREATE TABLE UserEntity (isActive boolean not null, id bigint generated by default as identity, address varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), username varchar(255) unique, primary key (id));

ALTER TABLE IF EXISTS Trainee ADD CONSTRAINT FK2ia9wlyrygv5pc1lgec180nvx FOREIGN KEY (user_id) REFERENCES UserEntity;
ALTER TABLE IF EXISTS Trainer ADD CONSTRAINT FKoqrs0ty0bq7ro5x2kecq6ln6j FOREIGN KEY (user_id) REFERENCES UserEntity;
ALTER TABLE IF EXISTS Trainer_TrainingType ADD CONSTRAINT FK2sjhiy8fck342jd3dvmh6ftn0 FOREIGN KEY (specializations_id) REFERENCES TrainingType;
ALTER TABLE IF EXISTS Trainer_TrainingType ADD CONSTRAINT FKs6jqgisdlm3lu854yngt7fc8h FOREIGN KEY (Trainer_id) REFERENCES Trainer;
ALTER TABLE IF EXISTS Training ADD CONSTRAINT FKdo1ud9tn6ndbk4vlv0w59ace7 FOREIGN KEY (trainee_id) REFERENCES Trainee;
ALTER TABLE IF EXISTS Training ADD CONSTRAINT FK7nior8x5718iqu50ixrhbphkn FOREIGN KEY (trainer_id) REFERENCES Trainer;
ALTER TABLE IF EXISTS Training ADD CONSTRAINT FK5slu6el1x5qvtwmg91g6w36bk FOREIGN KEY (trainingType_id) REFERENCES TrainingType;